# Generated by the vetiver package; edit with care

library(pins)
library(plumber)
library(rapidoc)
library(vetiver)

# Packages needed to generate model predictions
if (FALSE) {
  library(baguette)
  library(parsnip)
  library(recipes)
  library(rpart)
  library(themis)
  library(workflows)
}
b <- board_rsconnect("envvar", server = "https://colorado.rstudio.com/rsc")
v <- vetiver_pin_read(b, "julia.silge/traffic-crash-model", version = "63769")
metrics <- tibble::as_tibble(v$metadata$user$metrics)

#* @plumber
function(pr) {
  pr %>%
    vetiver_api(v, debug = TRUE) %>%
    pr_get(path = "metrics", handler = function() metrics)
}
